### ISSUE TITLE
Charge = 0 for all Pruned/Packed GenParticles

### ISSUE THREAD

**Issue by klannon** [cms-ttH/ttH-13TeVMultiLeptons#5]
This seems like a bug, but if it's a feature, just close the issue.

**Comment by muell149** [comment]
I will add the charge shortly. For now you can get the charge via the pdg ID.

**Comment by klannon** [comment]
Yeah, but once you start dealing with hadrons, which can be neutral, that gets a lot more complicated.  For now, I'm just going to gloss over the treatment of charged vs neutrals in my attempt to calculate mini at Gen-level, but if it doesn't work, I might need to treat charged and neutrals slightly differently.

**Comment by muell149** [comment]
This has been fixed to grab the charges (0,+-1)  available from the relevant collection in the miniAOD

**Comment by matz-e** [comment]
Wouldn't you want to close the issue then? ;)

**Comment by muell149** [comment]
I wanted let @klannon have a chance to comment before closing.
